<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ajeet" name="BankingApp Test" tests="4" failures="1" timestamp="23 Jun 2021 08:08:24 GMT" time="72.732" errors="0">
  <testcase name="loginTest" time="5.94" classname="com.inetbanking.testCases.TC_LoginTest_001"/>
  <testcase name="loginDDT" time="0.0" classname="com.inetbanking.testCases.TC_LoginDDT_002">
    <skipped/>
  </testcase> <!-- loginDDT -->
  <testcase name="addNewCustomer" time="18.794" classname="com.inetbanking.testCases.TC_AddCustomerTest_003"/>
  <testcase name="login_and_editcustomer" time="16.176" classname="com.inetbanking.testCases.EditCustomer">
    <failure type="java.lang.AssertionError" message="expected [Customer details updated Successfully!!!] but found []">
      <![CDATA[java.lang.AssertionError: expected [Customer details updated Successfully!!!] but found []
	at com.inetbanking.testCases.EditCustomer.login_and_editcustomer(EditCustomer.java:42)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- login_and_editcustomer -->
</testsuite> <!-- BankingApp Test -->
